[build]
  command = "npm ci --include=optional && npm run build"
  publish = "dist"
  functions = "netlify/functions"   

[build.environment]
  NODE_VERSION = "20.19.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
